### ISSUE TITLE
Could have been a PR or a fork

### ISSUE THREAD

**Issue by erikmueller** [Mudassar045/cond-construct#2]
Hey there,

I noticed you copied `cond-flow` (and republished under `cond-construct`). Was there a reason for not forking the original repo and/or doing a PR with the typings?

**Comment by mudssrali** [comment]
Hi Erik,
Yes it's copied, it was just a learning attempt to publish package to npm
and use them and there's no other specific behind doing this. I should be
apologise for this act.
Yes you're right, I should give fork to it or just completely make new PR
to your repo. At the weekend I can change it into A PR and clearly
mentioned on the readme as forked from you.
